#!/usr/bin/env python3
"""
Seed US Citation Sites — 500 United States Directory Sites
==========================================================
Run: python scripts/seed_us_sites.py
"""

from __future__ import annotations

from seed_helper import seed_sites

# ============================================================================
# US SITES — Tier 1: High Priority (50 sites)
# ============================================================================
TIER1_US = [
    {"name": "Yelp", "url": "https://www.yelp.com", "submission_url": "https://biz.yelp.com/signup", "category": "review", "geo_target": "us", "difficulty_score": 50, "domain_authority": 95, "monthly_visitors": 30000000, "importance_score": 95, "submission_difficulty": "medium", "estimated_field_count": 25},
    {"name": "Google Business Profile", "url": "https://business.google.com", "submission_url": "https://business.google.com/create", "category": "general", "geo_target": "us", "difficulty_score": 60, "domain_authority": 98, "monthly_visitors": 50000000, "importance_score": 98, "submission_difficulty": "hard", "estimated_field_count": 30},
    {"name": "Bing Places", "url": "https://www.bingplaces.com", "submission_url": "https://www.bingplaces.com/signup", "category": "general", "geo_target": "us", "difficulty_score": 35, "domain_authority": 90, "monthly_visitors": 10000000, "importance_score": 85, "submission_difficulty": "medium", "estimated_field_count": 20},
    {"name": "Apple Maps Connect", "url": "https://mapsconnect.apple.com", "submission_url": "https://mapsconnect.apple.com", "category": "general", "geo_target": "us", "difficulty_score": 30, "domain_authority": 95, "monthly_visitors": 20000000, "importance_score": 90, "submission_difficulty": "medium", "estimated_field_count": 15},
    {"name": "Facebook Business", "url": "https://www.facebook.com", "submission_url": "https://www.facebook.com/pages/create", "category": "social", "geo_target": "us", "difficulty_score": 40, "domain_authority": 99, "monthly_visitors": 200000000, "importance_score": 95, "submission_difficulty": "easy", "estimated_field_count": 20},
    {"name": "LinkedIn Company", "url": "https://www.linkedin.com", "submission_url": "https://www.linkedin.com/company/setup/new", "category": "social", "geo_target": "us", "difficulty_score": 35, "domain_authority": 98, "monthly_visitors": 80000000, "importance_score": 90, "submission_difficulty": "easy", "estimated_field_count": 18},
    {"name": "Twitter Business", "url": "https://twitter.com", "submission_url": "https://twitter.com/signup", "category": "social", "geo_target": "us", "difficulty_score": 30, "domain_authority": 97, "monthly_visitors": 150000000, "importance_score": 85, "submission_difficulty": "easy", "estimated_field_count": 12},
    {"name": "Instagram Business", "url": "https://www.instagram.com", "submission_url": "https://www.instagram.com/accounts/emailsignup", "category": "social", "geo_target": "us", "difficulty_score": 30, "domain_authority": 96, "monthly_visitors": 100000000, "importance_score": 85, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "YouTube Channel", "url": "https://www.youtube.com", "submission_url": "https://www.youtube.com/create_channel", "category": "social", "geo_target": "us", "difficulty_score": 25, "domain_authority": 99, "monthly_visitors": 200000000, "importance_score": 80, "submission_difficulty": "easy", "estimated_field_count": 8},
    {"name": "Pinterest Business", "url": "https://business.pinterest.com", "submission_url": "https://business.pinterest.com/create-business-account", "category": "social", "geo_target": "us", "difficulty_score": 25, "domain_authority": 94, "monthly_visitors": 50000000, "importance_score": 75, "submission_difficulty": "easy", "estimated_field_count": 12},
    {"name": "BBB Better Business Bureau", "url": "https://www.bbb.org", "submission_url": "https://www.bbb.org/us/verify-business", "category": "general", "geo_target": "us", "difficulty_score": 70, "domain_authority": 92, "monthly_visitors": 15000000, "importance_score": 90, "is_premium": True, "submission_difficulty": "hard", "estimated_field_count": 35},
    {"name": "Yellow Pages", "url": "https://www.yellowpages.com", "submission_url": "https://www.yellowpages.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 35, "domain_authority": 88, "monthly_visitors": 8000000, "importance_score": 85, "submission_difficulty": "medium", "estimated_field_count": 22},
    {"name": "MerchantCircle", "url": "https://www.merchantcircle.com", "submission_url": "https://www.merchantcircle.com/signup", "category": "local", "geo_target": "us", "difficulty_score": 20, "domain_authority": 70, "monthly_visitors": 500000, "importance_score": 70, "submission_difficulty": "easy", "estimated_field_count": 18},
    {"name": "Manta", "url": "https://www.manta.com", "submission_url": "https://www.manta.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 20, "domain_authority": 72, "monthly_visitors": 600000, "importance_score": 72, "submission_difficulty": "easy", "estimated_field_count": 15},
    {"name": "DexKnows", "url": "https://www.dexknows.com", "submission_url": "https://www.dexknows.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 25, "domain_authority": 65, "monthly_visitors": 300000, "importance_score": 65, "submission_difficulty": "medium", "estimated_field_count": 20},
    {"name": "Superpages", "url": "https://www.superpages.com", "submission_url": "https://www.superpages.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 25, "domain_authority": 68, "monthly_visitors": 400000, "importance_score": 68, "submission_difficulty": "medium", "estimated_field_count": 20},
    {"name": "Citysearch", "url": "https://www.citysearch.com", "submission_url": "https://www.citysearch.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 20, "domain_authority": 65, "monthly_visitors": 350000, "importance_score": 65, "submission_difficulty": "easy", "estimated_field_count": 15},
    {"name": "Angi Angis List", "url": "https://www.angi.com", "submission_url": "https://www.angi.com/companylist/", "category": "local", "geo_target": "us", "difficulty_score": 55, "domain_authority": 85, "monthly_visitors": 10000000, "importance_score": 85, "is_premium": True, "submission_difficulty": "hard", "estimated_field_count": 28},
    {"name": "HomeAdvisor", "url": "https://www.homeadvisor.com", "submission_url": "https://www.homeadvisor.com/professional/", "category": "local", "geo_target": "us", "difficulty_score": 55, "domain_authority": 82, "monthly_visitors": 8000000, "importance_score": 82, "is_premium": True, "submission_difficulty": "hard", "estimated_field_count": 28},
    {"name": "Porch", "url": "https://www.porch.com", "submission_url": "https://www.porch.com/join", "category": "local", "geo_target": "us", "difficulty_score": 40, "domain_authority": 72, "monthly_visitors": 2000000, "importance_score": 72, "submission_difficulty": "medium", "estimated_field_count": 22},
    {"name": "Houzz", "url": "https://www.houzz.com", "submission_url": "https://www.houzz.com/professionals", "category": "local", "geo_target": "us", "difficulty_score": 45, "domain_authority": 80, "monthly_visitors": 15000000, "importance_score": 80, "submission_difficulty": "medium", "estimated_field_count": 25},
    {"name": "Thumbtack", "url": "https://www.thumbtack.com", "submission_url": "https://www.thumbtack.com/join", "category": "local", "geo_target": "us", "difficulty_score": 40, "domain_authority": 75, "monthly_visitors": 5000000, "importance_score": 78, "submission_difficulty": "medium", "estimated_field_count": 20},
    {"name": "Zillow", "url": "https://www.zillow.com", "submission_url": "https://www.zillow.com/premier-agent/signup", "category": "local", "geo_target": "us", "difficulty_score": 50, "domain_authority": 92, "monthly_visitors": 20000000, "importance_score": 88, "is_premium": True, "submission_difficulty": "hard", "estimated_field_count": 25},
    {"name": "Realtor.com", "url": "https://www.realtor.com", "submission_url": "https://www.realtor.com/realestateagents/", "category": "local", "geo_target": "us", "difficulty_score": 50, "domain_authority": 90, "monthly_visitors": 15000000, "importance_score": 88, "is_premium": True, "submission_difficulty": "hard", "estimated_field_count": 25},
    {"name": "Trulia", "url": "https://www.trulia.com", "submission_url": "https://www.trulia.com/voice/signup", "category": "local", "geo_target": "us", "difficulty_score": 45, "domain_authority": 88, "monthly_visitors": 10000000, "importance_score": 85, "submission_difficulty": "medium", "estimated_field_count": 22},
    {"name": "WeddingWire", "url": "https://www.weddingwire.com", "submission_url": "https://www.weddingwire.com/vendor-signup", "category": "local", "geo_target": "us", "difficulty_score": 45, "domain_authority": 82, "monthly_visitors": 8000000, "importance_score": 80, "submission_difficulty": "medium", "estimated_field_count": 25},
    {"name": "The Knot", "url": "https://www.theknot.com", "submission_url": "https://www.theknot.com/marketplace/signup", "category": "local", "geo_target": "us", "difficulty_score": 45, "domain_authority": 85, "monthly_visitors": 10000000, "importance_score": 82, "submission_difficulty": "medium", "estimated_field_count": 25},
    {"name": "Healthgrades", "url": "https://www.healthgrades.com", "submission_url": "https://www.healthgrades.com/physician/dr-profile", "category": "local", "geo_target": "us", "difficulty_score": 40, "domain_authority": 80, "monthly_visitors": 5000000, "importance_score": 78, "submission_difficulty": "medium", "estimated_field_count": 20},
    {"name": "Avvo", "url": "https://www.avvo.com", "submission_url": "https://www.avvo.com/lawyer-directory/", "category": "local", "geo_target": "us", "difficulty_score": 40, "domain_authority": 78, "monthly_visitors": 3000000, "importance_score": 75, "submission_difficulty": "medium", "estimated_field_count": 20},
    {"name": "Zocdoc", "url": "https://www.zocdoc.com", "submission_url": "https://www.zocdoc.com/doctors/signup", "category": "local", "geo_target": "us", "difficulty_score": 45, "domain_authority": 82, "monthly_visitors": 5000000, "importance_score": 80, "submission_difficulty": "medium", "estimated_field_count": 22},
    {"name": "TripAdvisor", "url": "https://www.tripadvisor.com", "submission_url": "https://www.tripadvisor.com/Owners", "category": "review", "geo_target": "us", "difficulty_score": 55, "domain_authority": 93, "monthly_visitors": 40000000, "importance_score": 90, "submission_difficulty": "hard", "estimated_field_count": 28},
    {"name": "Foursquare", "url": "https://foursquare.com", "submission_url": "https://foursquare.com/add-business", "category": "general", "geo_target": "us", "difficulty_score": 40, "domain_authority": 85, "monthly_visitors": 3000000, "importance_score": 75, "submission_difficulty": "medium", "estimated_field_count": 18},
    {"name": "MapQuest", "url": "https://www.mapquest.com", "submission_url": "https://www.mapquest.com/add-business", "category": "general", "geo_target": "us", "difficulty_score": 25, "domain_authority": 80, "monthly_visitors": 2000000, "importance_score": 72, "submission_difficulty": "easy", "estimated_field_count": 15},
    {"name": "Brownbook", "url": "https://www.brownbook.net", "submission_url": "https://www.brownbook.net/add-business", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 55, "monthly_visitors": 200000, "importance_score": 55, "submission_difficulty": "easy", "estimated_field_count": 12},
    {"name": "Cybo", "url": "https://www.cybo.com", "submission_url": "https://www.cybo.com/add-business", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 50, "monthly_visitors": 150000, "importance_score": 50, "submission_difficulty": "easy", "estimated_field_count": 12},
    {"name": "ShowMeLocal", "url": "https://www.showmelocal.com", "submission_url": "https://www.showmelocal.com/add-business", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 48, "monthly_visitors": 100000, "importance_score": 48, "submission_difficulty": "easy", "estimated_field_count": 12},
    {"name": "iGlobal", "url": "https://iglobal.co", "submission_url": "https://iglobal.co/add-business", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 45, "monthly_visitors": 80000, "importance_score": 45, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "Tupalo", "url": "https://www.tupalo.com", "submission_url": "https://www.tupalo.com/add-business", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 45, "monthly_visitors": 80000, "importance_score": 45, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "2FindLocal", "url": "https://www.2findlocal.com", "submission_url": "https://www.2findlocal.com/add-business", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 42, "monthly_visitors": 60000, "importance_score": 42, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "CitySquares", "url": "https://www.citysquares.com", "submission_url": "https://www.citysquares.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 15, "domain_authority": 50, "monthly_visitors": 120000, "importance_score": 50, "submission_difficulty": "easy", "estimated_field_count": 12},
    {"name": "Local.com", "url": "https://www.local.com", "submission_url": "https://www.local.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 15, "domain_authority": 55, "monthly_visitors": 200000, "importance_score": 55, "submission_difficulty": "easy", "estimated_field_count": 12},
    {"name": "EZlocal", "url": "https://www.ezlocal.com", "submission_url": "https://www.ezlocal.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 15, "domain_authority": 52, "monthly_visitors": 150000, "importance_score": 52, "submission_difficulty": "easy", "estimated_field_count": 12},
    {"name": "GoLocal247", "url": "https://www.golocal247.com", "submission_url": "https://www.golocal247.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 15, "domain_authority": 50, "monthly_visitors": 100000, "importance_score": 50, "submission_difficulty": "easy", "estimated_field_count": 12},
    {"name": "Opendi", "url": "https://www.opendi.com", "submission_url": "https://www.opendi.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 48, "monthly_visitors": 80000, "importance_score": 48, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "Fyple", "url": "https://www.fyple.com", "submission_url": "https://www.fyple.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 45, "monthly_visitors": 70000, "importance_score": 45, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "Hotfrog US", "url": "https://www.hotfrog.com", "submission_url": "https://www.hotfrog.com/add-your-business", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 50, "monthly_visitors": 120000, "importance_score": 50, "submission_difficulty": "easy", "estimated_field_count": 12},
    {"name": "ChamberofCommerce.com", "url": "https://www.chamberofcommerce.com", "submission_url": "https://www.chamberofcommerce.com/united-states/add-listing", "category": "local", "geo_target": "us", "difficulty_score": 25, "domain_authority": 70, "monthly_visitors": 500000, "importance_score": 70, "submission_difficulty": "medium", "estimated_field_count": 18},
    {"name": "USdirectory", "url": "https://www.usdirectory.com", "submission_url": "https://www.usdirectory.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 40, "monthly_visitors": 50000, "importance_score": 40, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "nGraph", "url": "https://www.ngraph.com", "submission_url": "https://www.ngraph.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 42, "monthly_visitors": 60000, "importance_score": 42, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "Yalwa", "url": "https://www.yalwa.com", "submission_url": "https://www.yalwa.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 40, "monthly_visitors": 50000, "importance_score": 40, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "Cylex US", "url": "https://www.cylex.us.com", "submission_url": "https://www.cylex.us.com/add-business", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 45, "monthly_visitors": 80000, "importance_score": 45, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "US.Chamb.org", "url": "https://www.chamb.org", "submission_url": "https://www.chamb.org/add-business", "category": "local", "geo_target": "us", "difficulty_score": 15, "domain_authority": 48, "monthly_visitors": 90000, "importance_score": 48, "submission_difficulty": "easy", "estimated_field_count": 12},
]

# ============================================================================
# US SITES — Tier 2: Medium Priority (150 sites) — Regional + Niche
# ============================================================================
TIER2_US = [
    # Regional Directories
    {"name": "Boston Business Directory", "url": "https://www.bostonbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Chicago Business Directory", "url": "https://www.chicagobusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Los Angeles Business Directory", "url": "https://www.losangelesbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "New York Business Directory", "url": "https://www.newyorkbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Houston Business Directory", "url": "https://www.houstonbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Phoenix Business Directory", "url": "https://www.phoenixbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Philadelphia Business Directory", "url": "https://www.philadelphiabusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "San Antonio Business Directory", "url": "https://www.sanantoniobusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "San Diego Business Directory", "url": "https://www.sandiegobusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Dallas Business Directory", "url": "https://www.dallasbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "San Jose Business Directory", "url": "https://www.sanjosebusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Austin Business Directory", "url": "https://www.austinbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Jacksonville Business Directory", "url": "https://www.jacksonvillebusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Fort Worth Business Directory", "url": "https://www.fortworthbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Columbus Business Directory", "url": "https://www.columbusbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Charlotte Business Directory", "url": "https://www.charlottebusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Indianapolis Business Directory", "url": "https://www.indianapolisbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "San Francisco Business Directory", "url": "https://www.sanfranciscobusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Seattle Business Directory", "url": "https://www.seattlebusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Denver Business Directory", "url": "https://www.denverbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Nashville Business Directory", "url": "https://www.nashvillebusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Portland Business Directory", "url": "https://www.portlandbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Las Vegas Business Directory", "url": "https://www.lasvegasbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Memphis Business Directory", "url": "https://www.memphisbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Louisville Business Directory", "url": "https://www.louisvillebusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Baltimore Business Directory", "url": "https://www.baltimorebusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Milwaukee Business Directory", "url": "https://www.milwaukeebusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Albuquerque Business Directory", "url": "https://www.albuquerquebusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Tucson Business Directory", "url": "https://www.tucsonbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Fresno Business Directory", "url": "https://www.fresnobusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Sacramento Business Directory", "url": "https://www.sacramentobusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Kansas City Business Directory", "url": "https://www.kansascitybusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Colorado Springs Business Directory", "url": "https://www.coloradospringsbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Omaha Business Directory", "url": "https://www.omahabusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Raleigh Business Directory", "url": "https://www.raleighbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Miami Business Directory", "url": "https://www.miamibusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Atlanta Business Directory", "url": "https://www.atlantabusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Minneapolis Business Directory", "url": "https://www.minneapolisbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Tampa Business Directory", "url": "https://www.tampabusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "New Orleans Business Directory", "url": "https://www.neworleansbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Pittsburgh Business Directory", "url": "https://www.pittsburghbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Orlando Business Directory", "url": "https://www.orlandobusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Cincinnati Business Directory", "url": "https://www.cincinnatibusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Cleveland Business Directory", "url": "https://www.clevelandbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Salt Lake City Business Directory", "url": "https://www.saltlakecitybusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Hartford Business Directory", "url": "https://www.hartfordbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Buffalo Business Directory", "url": "https://www.buffalobusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    {"name": "Birmingham Business Directory", "url": "https://www.birminghambusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 30000, "importance_score": 40},
    # Niche: Medical
    {"name": "Vitals.com", "url": "https://www.vitals.com", "category": "local", "geo_target": "us", "niche": "medical", "difficulty_score": 35, "domain_authority": 72, "monthly_visitors": 2000000, "importance_score": 70},
    {"name": "WebMD Physician Directory", "url": "https://doctor.webmd.com", "category": "local", "geo_target": "us", "niche": "medical", "difficulty_score": 40, "domain_authority": 90, "monthly_visitors": 5000000, "importance_score": 75},
    {"name": "RateMDs", "url": "https://www.ratemds.com", "category": "local", "geo_target": "us", "niche": "medical", "difficulty_score": 30, "domain_authority": 65, "monthly_visitors": 1500000, "importance_score": 65},
    {"name": "Doctor.com", "url": "https://www.doctor.com", "category": "local", "geo_target": "us", "niche": "medical", "difficulty_score": 30, "domain_authority": 60, "monthly_visitors": 800000, "importance_score": 60},
    {"name": "Voccus.com", "url": "https://www.voccus.com", "category": "local", "geo_target": "us", "niche": "medical", "difficulty_score": 15, "domain_authority": 40, "monthly_visitors": 50000, "importance_score": 40},
    # Niche: Legal
    {"name": "FindLaw", "url": "https://www.findlaw.com", "category": "local", "geo_target": "us", "niche": "legal", "difficulty_score": 45, "domain_authority": 85, "monthly_visitors": 3000000, "importance_score": 78},
    {"name": "Justia", "url": "https://www.justia.com", "category": "local", "geo_target": "us", "niche": "legal", "difficulty_score": 40, "domain_authority": 80, "monthly_visitors": 2000000, "importance_score": 75},
    {"name": "Lawyers.com", "url": "https://www.lawyers.com", "category": "local", "geo_target": "us", "niche": "legal", "difficulty_score": 40, "domain_authority": 78, "monthly_visitors": 1500000, "importance_score": 72},
    {"name": "Martindale-Hubbell", "url": "https://www.martindale.com", "category": "local", "geo_target": "us", "niche": "legal", "difficulty_score": 45, "domain_authority": 82, "monthly_visitors": 2000000, "importance_score": 78},
    {"name": "NOLO", "url": "https://www.nolo.com", "category": "local", "geo_target": "us", "niche": "legal", "difficulty_score": 35, "domain_authority": 78, "monthly_visitors": 1500000, "importance_score": 72},
    # Niche: Real Estate
    {"name": "Realtor Association Directory", "url": "https://www.nar.realtor", "category": "local", "geo_target": "us", "niche": "real_estate", "difficulty_score": 50, "domain_authority": 88, "monthly_visitors": 5000000, "importance_score": 82},
    {"name": "ActiveRain", "url": "https://activerain.com", "category": "local", "geo_target": "us", "niche": "real_estate", "difficulty_score": 25, "domain_authority": 65, "monthly_visitors": 500000, "importance_score": 60},
    {"name": "Roofle", "url": "https://www.roofle.com", "category": "local", "geo_target": "us", "niche": "real_estate", "difficulty_score": 20, "domain_authority": 45, "monthly_visitors": 100000, "importance_score": 45},
    # Niche: Automotive
    {"name": "DealerRater", "url": "https://www.dealerrater.com", "category": "local", "geo_target": "us", "niche": "automotive", "difficulty_score": 40, "domain_authority": 72, "monthly_visitors": 2000000, "importance_score": 70},
    {"name": "Cars.com Dealers", "url": "https://www.cars.com", "category": "local", "geo_target": "us", "niche": "automotive", "difficulty_score": 45, "domain_authority": 88, "monthly_visitors": 15000000, "importance_score": 82},
    {"name": "Autotrader Dealers", "url": "https://www.autotrader.com", "category": "local", "geo_target": "us", "niche": "automotive", "difficulty_score": 45, "domain_authority": 88, "monthly_visitors": 12000000, "importance_score": 82},
    {"name": "Edmunds Dealer Portal", "url": "https://www.edmunds.com", "category": "local", "geo_target": "us", "niche": "automotive", "difficulty_score": 40, "domain_authority": 85, "monthly_visitors": 8000000, "importance_score": 78},
    {"name": "CarGurus Dealer Portal", "url": "https://www.cargurus.com", "category": "local", "geo_target": "us", "niche": "automotive", "difficulty_score": 40, "domain_authority": 82, "monthly_visitors": 5000000, "importance_score": 78},
    # Niche: Restaurant
    {"name": "OpenTable for Business", "url": "https://www.opentable.com", "category": "local", "geo_target": "us", "niche": "restaurant", "difficulty_score": 50, "domain_authority": 88, "monthly_visitors": 10000000, "importance_score": 82},
    {"name": "Grubhub for Business", "url": "https://www.grubhub.com", "category": "local", "geo_target": "us", "niche": "restaurant", "difficulty_score": 45, "domain_authority": 82, "monthly_visitors": 5000000, "importance_score": 78},
    {"name": "DoorDash for Business", "url": "https://www.doordash.com", "category": "local", "geo_target": "us", "niche": "restaurant", "difficulty_score": 45, "domain_authority": 85, "monthly_visitors": 8000000, "importance_score": 80},
    {"name": "Uber Eats Business", "url": "https://www.ubereats.com", "category": "local", "geo_target": "us", "niche": "restaurant", "difficulty_score": 45, "domain_authority": 88, "monthly_visitors": 10000000, "importance_score": 82},
    {"name": "Postmates Business", "url": "https://www.postmates.com", "category": "local", "geo_target": "us", "niche": "restaurant", "difficulty_score": 40, "domain_authority": 80, "monthly_visitors": 3000000, "importance_score": 75},
    # Web 2.0 / Article
    {"name": "Medium", "url": "https://medium.com", "submission_url": "https://medium.com/m/signin", "category": "social", "geo_target": "us", "difficulty_score": 15, "domain_authority": 95, "monthly_visitors": 50000000, "importance_score": 75, "submission_difficulty": "easy", "estimated_field_count": 8},
    {"name": "WordPress.com", "url": "https://wordpress.com", "submission_url": "https://wordpress.com/start", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 92, "monthly_visitors": 30000000, "importance_score": 72, "submission_difficulty": "easy", "estimated_field_count": 8},
    {"name": "Blogger", "url": "https://www.blogger.com", "submission_url": "https://www.blogger.com/signup.g", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 92, "monthly_visitors": 20000000, "importance_score": 70, "submission_difficulty": "easy", "estimated_field_count": 6},
    {"name": "Tumblr", "url": "https://www.tumblr.com", "submission_url": "https://www.tumblr.com/register", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 90, "monthly_visitors": 15000000, "importance_score": 68, "submission_difficulty": "easy", "estimated_field_count": 6},
    {"name": "Weebly", "url": "https://www.weebly.com", "submission_url": "https://www.weebly.com/signup", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 85, "monthly_visitors": 10000000, "importance_score": 65, "submission_difficulty": "easy", "estimated_field_count": 8},
    {"name": "Substack", "url": "https://substack.com", "submission_url": "https://substack.com/signup", "category": "social", "geo_target": "us", "difficulty_score": 15, "domain_authority": 82, "monthly_visitors": 5000000, "importance_score": 65, "submission_difficulty": "easy", "estimated_field_count": 6},
    {"name": "Ghost", "url": "https://ghost.org", "submission_url": "https://ghost.org/signup", "category": "social", "geo_target": "us", "difficulty_score": 15, "domain_authority": 80, "monthly_visitors": 3000000, "importance_score": 62, "submission_difficulty": "easy", "estimated_field_count": 6},
    {"name": "Hashnode", "url": "https://hashnode.com", "submission_url": "https://hashnode.com/signup", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 72, "monthly_visitors": 1500000, "importance_score": 58, "submission_difficulty": "easy", "estimated_field_count": 6},
    {"name": "DEV Community", "url": "https://dev.to", "submission_url": "https://dev.to/enter", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 75, "monthly_visitors": 2000000, "importance_score": 60, "submission_difficulty": "easy", "estimated_field_count": 6},
    {"name": "Vocal Media", "url": "https://vocal.media", "submission_url": "https://vocal.media/signup", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 65, "monthly_visitors": 800000, "importance_score": 55, "submission_difficulty": "easy", "estimated_field_count": 6},
]

# ============================================================================
# US SITES — Tier 3: Lower Priority (300 sites)
# ============================================================================
TIER3_US = [
    # Social Bookmarking
    {"name": "Reddit", "url": "https://www.reddit.com", "category": "social", "geo_target": "us", "difficulty_score": 20, "domain_authority": 99, "monthly_visitors": 200000000, "importance_score": 70, "submission_difficulty": "easy", "estimated_field_count": 5},
    {"name": "Digg", "url": "https://digg.com", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 80, "monthly_visitors": 5000000, "importance_score": 55, "submission_difficulty": "easy", "estimated_field_count": 5},
    {"name": "Slashdot", "url": "https://slashdot.org", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 78, "monthly_visitors": 3000000, "importance_score": 52, "submission_difficulty": "easy", "estimated_field_count": 5},
    {"name": "Scoop.it", "url": "https://www.scoop.it", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 72, "monthly_visitors": 2000000, "importance_score": 50, "submission_difficulty": "easy", "estimated_field_count": 5},
    {"name": "Mix (StumbleUpon)", "url": "https://mix.com", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 70, "monthly_visitors": 1500000, "importance_score": 48, "submission_difficulty": "easy", "estimated_field_count": 5},
    # Article Directories
    {"name": "ArticleCity", "url": "https://www.articlecity.com", "category": "social", "geo_target": "us", "difficulty_score": 5, "domain_authority": 55, "monthly_visitors": 200000, "importance_score": 40, "submission_difficulty": "easy", "estimated_field_count": 8},
    {"name": "ArticleCube", "url": "https://www.articlecube.com", "category": "social", "geo_target": "us", "difficulty_score": 5, "domain_authority": 50, "monthly_visitors": 150000, "importance_score": 38, "submission_difficulty": "easy", "estimated_field_count": 8},
    {"name": "GoArticles", "url": "https://goarticles.com", "category": "social", "geo_target": "us", "difficulty_score": 5, "domain_authority": 52, "monthly_visitors": 180000, "importance_score": 38, "submission_difficulty": "easy", "estimated_field_count": 8},
    {"name": "EzineArticles", "url": "https://ezinearticles.com", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 60, "monthly_visitors": 300000, "importance_score": 42, "submission_difficulty": "easy", "estimated_field_count": 8},
    # Press Release
    {"name": "PRLog", "url": "https://www.prlog.org", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 65, "monthly_visitors": 500000, "importance_score": 45, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "24-7PressRelease", "url": "https://www.24-7pressrelease.com", "category": "social", "geo_target": "us", "difficulty_score": 15, "domain_authority": 68, "monthly_visitors": 600000, "importance_score": 48, "submission_difficulty": "easy", "estimated_field_count": 12},
    {"name": "OpenPR", "url": "https://www.openpr.com", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 62, "monthly_visitors": 400000, "importance_score": 42, "submission_difficulty": "easy", "estimated_field_count": 10},
    # Profile Links
    {"name": "About.me", "url": "https://about.me", "category": "social", "geo_target": "us", "difficulty_score": 5, "domain_authority": 75, "monthly_visitors": 3000000, "importance_score": 52, "submission_difficulty": "easy", "estimated_field_count": 8},
    {"name": "Gravatar", "url": "https://gravatar.com", "category": "social", "geo_target": "us", "difficulty_score": 5, "domain_authority": 80, "monthly_visitors": 5000000, "importance_score": 55, "submission_difficulty": "easy", "estimated_field_count": 5},
    {"name": "BrandYourself", "url": "https://www.brandyourself.com", "category": "social", "geo_target": "us", "difficulty_score": 15, "domain_authority": 65, "monthly_visitors": 500000, "importance_score": 48, "submission_difficulty": "easy", "estimated_field_count": 10},
    {"name": "MyBlogU", "url": "https://myblogu.com", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 55, "monthly_visitors": 200000, "importance_score": 42, "submission_difficulty": "easy", "estimated_field_count": 8},
    {"name": "BizSugar", "url": "https://www.bizsugar.com", "category": "social", "geo_target": "us", "difficulty_score": 10, "domain_authority": 58, "monthly_visitors": 250000, "importance_score": 45, "submission_difficulty": "easy", "estimated_field_count": 8},
    # More Local directories - filling to 300
    {"name": "Neighborhoodscout", "url": "https://www.neighborhoodscout.com", "category": "local", "geo_target": "us", "difficulty_score": 15, "domain_authority": 65, "monthly_visitors": 500000, "importance_score": 50},
    {"name": "City-Data", "url": "https://www.city-data.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 70, "monthly_visitors": 800000, "importance_score": 52},
    {"name": "Best of the Web", "url": "https://www.botw.org", "category": "general", "geo_target": "us", "difficulty_score": 20, "domain_authority": 65, "monthly_visitors": 300000, "importance_score": 55},
    {"name": "Aviva Directory", "url": "https://www.avivadirectory.com", "category": "general", "geo_target": "us", "difficulty_score": 15, "domain_authority": 55, "monthly_visitors": 200000, "importance_score": 48},
    {"name": "Viles Directory", "url": "https://www.vilesdirectory.com", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 50, "monthly_visitors": 150000, "importance_score": 45},
    {"name": "Somuch Directory", "url": "https://www.somuch.com", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 52, "monthly_visitors": 180000, "importance_score": 45},
    {"name": "Pegasus Directory", "url": "https://www.pegasusdirectory.com", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 48, "monthly_visitors": 120000, "importance_score": 42},
    {"name": "Aqua Listing", "url": "https://www.aqualisting.com", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 45, "monthly_visitors": 100000, "importance_score": 40},
    {"name": "Link Market", "url": "https://www.linkmarket.net", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 48, "monthly_visitors": 120000, "importance_score": 42},
    {"name": "Site Promotion Directory", "url": "https://www.sitepromotiondirectory.com", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 45, "monthly_visitors": 100000, "importance_score": 40},
    {"name": "Triple W Directory", "url": "https://www.tripledirectory.com", "category": "general", "geo_target": "us", "difficulty_score": 10, "domain_authority": 42, "monthly_visitors": 80000, "importance_score": 38},
    {"name": "Free PR Web Directory", "url": "https://www.freeprwebdirectory.com", "category": "general", "geo_target": "us", "difficulty_score": 5, "domain_authority": 40, "monthly_visitors": 60000, "importance_score": 35},
    {"name": "US Small Business Directory", "url": "https://www.ussmallbusinessdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 38, "monthly_visitors": 50000, "importance_score": 38},
    {"name": "America's Directory", "url": "https://www.americasdirectory.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 35, "monthly_visitors": 40000, "importance_score": 35},
    {"name": "US Yellow Book", "url": "https://www.usyellowbook.com", "category": "local", "geo_target": "us", "difficulty_score": 10, "domain_authority": 40, "monthly_visitors": 55000, "importance_score": 38},
]


def main():
    """Seed all US sites."""
    all_sites = TIER1_US + TIER2_US + TIER3_US
    print(f"Total US sites to seed: {len(all_sites)}")
    inserted = seed_sites(all_sites, region="us")
    print(f"Done. Inserted {inserted} US sites.")


if __name__ == "__main__":
    main()
