"""add keyword research table

Revision ID: 0d50d93a2214
Revises: 002
Create Date: 2026-05-13 22:26:27.245274
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '0d50d93a2214'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('street_address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=False),
    sa.Column('primary_category', sa.String(length=100), nullable=False),
    sa.Column('secondary_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_client_id'), 'business_profiles', ['client_id'], unique=False)
    op.create_index(op.f('ix_business_profiles_tenant_id'), 'business_profiles', ['tenant_id'], unique=False)
    op.create_table('citation_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=255), nullable=False),
    sa.Column('directory_adapter', sa.String(length=100), nullable=False),
    sa.Column('submission_status', sa.String(length=50), nullable=False),
    sa.Column('submission_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification_state', sa.String(length=50), nullable=False),
    sa.Column('live_url', sa.String(length=500), nullable=True),
    sa.Column('nap_consistency_score', sa.Float(), nullable=True),
    sa.Column('automation_trace_url', sa.String(length=500), nullable=True),
    sa.Column('screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_submissions_profile_id'), 'citation_submissions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_citation_submissions_tenant_id'), 'citation_submissions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_citation_submissions_workflow_run_id'), 'citation_submissions', ['workflow_run_id'], unique=False)
    op.alter_column('acquired_links', 'anchor_text',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('acquired_links', 'link_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('acquired_links', 'status',
               existing_type=postgresql.ENUM('pending_verification', 'verified_live', 'verified_nofollow', 'removed', 'broken', name='link_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('acquired_links', 'domain_authority_at_acquisition',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('acquired_links', 'check_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'acquired_links', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('approval_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', 'modification_requested', 'expired', 'delegated', name='approval_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('approval_requests', 'ai_risk_summary',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('approval_requests', 'decision_reason',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('approval_requests', 'escalation_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_approval_sla'), table_name='approval_requests')
    op.create_foreign_key(None, 'approval_requests', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('backlink_campaigns', 'status',
               existing_type=postgresql.ENUM('draft', 'prospecting', 'scoring', 'outreach_prep', 'awaiting_approval', 'active', 'paused', 'monitoring', 'complete', 'cancelled', name='campaign_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'target_link_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'acquired_link_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'total_prospects',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'total_emails_sent',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'reply_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'acquisition_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'health_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_campaigns_status_tenant'), table_name='backlink_campaigns')
    op.create_foreign_key(None, 'backlink_campaigns', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('backlink_prospects', 'status',
               existing_type=postgresql.ENUM('new', 'scored', 'approved', 'rejected', 'outreach_queued', 'contacted', 'replied', 'link_acquired', 'link_lost', 'unresponsive', name='prospect_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'domain_authority',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'relevance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'spam_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'traffic_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'composite_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_prospects_composite'), table_name='backlink_prospects')
    op.create_foreign_key(None, 'backlink_prospects', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('clients', 'onboarding_status',
               existing_type=postgresql.ENUM('pending', 'collecting', 'validating', 'ai_enrichment', 'awaiting_approval', 'complete', 'failed_validation', 'ai_failed', 'rejected', name='onboarding_status'),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'clients', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('keyword_clusters', 'total_volume',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keyword_clusters', 'avg_difficulty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keyword_clusters', 'keyword_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keyword_clusters', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keyword_clusters', 'status',
               existing_type=postgresql.ENUM('draft', 'pending_approval', 'approved', 'rejected', 'archived', name='cluster_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keyword_clusters', 'ai_rationale',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'keyword_clusters', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('keywords', 'search_volume',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keywords', 'difficulty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keywords', 'cpc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keywords', 'competition',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keywords', 'is_seed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_keywords_difficulty'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_volume'), table_name='keywords')
    op.create_foreign_key(None, 'keywords', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('outreach_threads', 'status',
               existing_type=postgresql.ENUM('draft', 'queued', 'sent', 'delivered', 'opened', 'replied', 'bounced', 'spam_reported', 'unsubscribed', 'link_acquired', name='thread_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('outreach_threads', 'body_html',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('outreach_threads', 'follow_up_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('outreach_threads', 'max_follow_ups',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('outreach_threads', 'provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('outreach_threads', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_threads_sent_at'), table_name='outreach_threads')
    op.create_foreign_key(None, 'outreach_threads', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tenants', 'plan',
               existing_type=postgresql.ENUM('starter', 'growth', 'enterprise', name='tenant_plan'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'tenant_admin', 'manager', 'seo_analyst', 'outreach_specialist', 'report_analyst', 'client', name='user_role'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'tenant_admin', 'manager', 'seo_analyst', 'outreach_specialist', 'report_analyst', 'client', name='user_role'),
               server_default=sa.text("'seo_analyst'::user_role"),
               existing_nullable=False)
    op.alter_column('tenants', 'plan',
               existing_type=postgresql.ENUM('starter', 'growth', 'enterprise', name='tenant_plan'),
               server_default=sa.text("'starter'::tenant_plan"),
               existing_nullable=False)
    op.drop_constraint(None, 'outreach_threads', type_='foreignkey')
    op.create_index(op.f('ix_threads_sent_at'), 'outreach_threads', ['sent_at'], unique=False)
    op.alter_column('outreach_threads', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('outreach_threads', 'provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'''sendgrid'''::character varying"),
               existing_nullable=False)
    op.alter_column('outreach_threads', 'max_follow_ups',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('outreach_threads', 'follow_up_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('outreach_threads', 'body_html',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('outreach_threads', 'status',
               existing_type=postgresql.ENUM('draft', 'queued', 'sent', 'delivered', 'opened', 'replied', 'bounced', 'spam_reported', 'unsubscribed', 'link_acquired', name='thread_status'),
               server_default=sa.text("'draft'::thread_status"),
               existing_nullable=False)
    op.drop_constraint(None, 'keywords', type_='foreignkey')
    op.create_index(op.f('ix_keywords_volume'), 'keywords', ['search_volume'], unique=False)
    op.create_index(op.f('ix_keywords_difficulty'), 'keywords', ['difficulty'], unique=False)
    op.alter_column('keywords', 'is_seed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('keywords', 'competition',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('keywords', 'cpc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('keywords', 'difficulty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('keywords', 'search_volume',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'keyword_clusters', type_='foreignkey')
    op.alter_column('keyword_clusters', 'ai_rationale',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('keyword_clusters', 'status',
               existing_type=postgresql.ENUM('draft', 'pending_approval', 'approved', 'rejected', 'archived', name='cluster_status'),
               server_default=sa.text("'draft'::cluster_status"),
               existing_nullable=False)
    op.alter_column('keyword_clusters', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('keyword_clusters', 'keyword_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('keyword_clusters', 'avg_difficulty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('keyword_clusters', 'total_volume',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.alter_column('clients', 'onboarding_status',
               existing_type=postgresql.ENUM('pending', 'collecting', 'validating', 'ai_enrichment', 'awaiting_approval', 'complete', 'failed_validation', 'ai_failed', 'rejected', name='onboarding_status'),
               server_default=sa.text("'pending'::onboarding_status"),
               existing_nullable=False)
    op.drop_constraint(None, 'backlink_prospects', type_='foreignkey')
    op.create_index(op.f('ix_prospects_composite'), 'backlink_prospects', ['composite_score'], unique=False)
    op.alter_column('backlink_prospects', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'composite_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'traffic_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'spam_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'relevance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'domain_authority',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('backlink_prospects', 'status',
               existing_type=postgresql.ENUM('new', 'scored', 'approved', 'rejected', 'outreach_queued', 'contacted', 'replied', 'link_acquired', 'link_lost', 'unresponsive', name='prospect_status'),
               server_default=sa.text("'new'::prospect_status"),
               existing_nullable=False)
    op.drop_constraint(None, 'backlink_campaigns', type_='foreignkey')
    op.create_index(op.f('ix_campaigns_status_tenant'), 'backlink_campaigns', ['tenant_id', 'status'], unique=False)
    op.alter_column('backlink_campaigns', 'health_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'acquisition_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'reply_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'total_emails_sent',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'total_prospects',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'acquired_link_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'target_link_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('backlink_campaigns', 'status',
               existing_type=postgresql.ENUM('draft', 'prospecting', 'scoring', 'outreach_prep', 'awaiting_approval', 'active', 'paused', 'monitoring', 'complete', 'cancelled', name='campaign_status'),
               server_default=sa.text("'draft'::campaign_status"),
               existing_nullable=False)
    op.drop_constraint(None, 'approval_requests', type_='foreignkey')
    op.create_index(op.f('ix_approval_sla'), 'approval_requests', ['sla_deadline'], unique=False)
    op.alter_column('approval_requests', 'escalation_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('approval_requests', 'decision_reason',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('approval_requests', 'ai_risk_summary',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('approval_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', 'modification_requested', 'expired', 'delegated', name='approval_status'),
               server_default=sa.text("'pending'::approval_status"),
               existing_nullable=False)
    op.drop_constraint(None, 'acquired_links', type_='foreignkey')
    op.alter_column('acquired_links', 'check_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('acquired_links', 'domain_authority_at_acquisition',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('acquired_links', 'status',
               existing_type=postgresql.ENUM('pending_verification', 'verified_live', 'verified_nofollow', 'removed', 'broken', name='link_status'),
               server_default=sa.text("'pending_verification'::link_status"),
               existing_nullable=False)
    op.alter_column('acquired_links', 'link_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'''dofollow'''::character varying"),
               existing_nullable=False)
    op.alter_column('acquired_links', 'anchor_text',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_citation_submissions_workflow_run_id'), table_name='citation_submissions')
    op.drop_index(op.f('ix_citation_submissions_tenant_id'), table_name='citation_submissions')
    op.drop_index(op.f('ix_citation_submissions_profile_id'), table_name='citation_submissions')
    op.drop_table('citation_submissions')
    op.drop_index(op.f('ix_business_profiles_tenant_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_client_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
