"""add_phase6_observability_tables

Revision ID: 0fc31328153b
Revises: 0e5262dcfbdb
Create Date: 2026-05-19 15:44:45.331525
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '0fc31328153b'
down_revision: Union[str, None] = '0e5262dcfbdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('execution_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trail_logs_event_type'), 'audit_trail_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_trail_logs_tenant_id'), 'audit_trail_logs', ['tenant_id'], unique=False)
    op.create_table('compliance_results',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('banned_words_found', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('max_sentence_length_violated', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_results_entity_id'), 'compliance_results', ['entity_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_tenant_id'), 'compliance_results', ['tenant_id'], unique=False)
    op.create_table('provider_health_metrics',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('circuit_breaker_state', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_health_metrics_provider_name'), 'provider_health_metrics', ['provider_name'], unique=False)
    op.create_index(op.f('ix_provider_health_metrics_tenant_id'), 'provider_health_metrics', ['tenant_id'], unique=False)
    op.create_table('campaign_timeline_events',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('step_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['backlink_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_timeline_events_campaign_id'), 'campaign_timeline_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_timeline_events_tenant_id'), 'campaign_timeline_events', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_operational_events_created_at'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_type'), table_name='operational_events')
    op.drop_table('operational_events')
    op.alter_column('business_intelligence_events', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('business_intelligence_events', 'delta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('business_intelligence_events', 'action_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('business_intelligence_events', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_bie_domain'), table_name='business_intelligence_events')
    op.drop_index(op.f('idx_bie_occurred'), table_name='business_intelligence_events')
    op.drop_index(op.f('idx_bie_type'), table_name='business_intelligence_events')
    op.create_index(op.f('ix_business_intelligence_events_domain'), 'business_intelligence_events', ['domain'], unique=False)
    op.create_index(op.f('ix_business_intelligence_events_entity_id'), 'business_intelligence_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_business_intelligence_events_event_type'), 'business_intelligence_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_business_intelligence_events_tenant_id'), 'business_intelligence_events', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'business_intelligence_events', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('campaign_health_snapshots', 'acquisition_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('campaign_health_snapshots', 'reply_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('campaign_health_snapshots', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('campaign_health_snapshots', 'momentum',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('campaign_health_snapshots', 'velocity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('campaign_health_snapshots', 'snapshot_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_chs_campaign'), table_name='campaign_health_snapshots')
    op.drop_index(op.f('idx_chs_captured'), table_name='campaign_health_snapshots')
    op.create_index(op.f('ix_campaign_health_snapshots_campaign_id'), 'campaign_health_snapshots', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_health_snapshots_tenant_id'), 'campaign_health_snapshots', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'campaign_health_snapshots', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('keyword_metric_snapshots', 'search_volume',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keyword_metric_snapshots', 'difficulty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keyword_metric_snapshots', 'cpc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('keyword_metric_snapshots', 'serp_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('keyword_metric_snapshots', 'opportunity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_kms_captured'), table_name='keyword_metric_snapshots')
    op.drop_index(op.f('idx_kms_keyword'), table_name='keyword_metric_snapshots')
    op.create_index(op.f('ix_keyword_metric_snapshots_cluster_id'), 'keyword_metric_snapshots', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_keyword_metric_snapshots_keyword_id'), 'keyword_metric_snapshots', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_metric_snapshots_tenant_id'), 'keyword_metric_snapshots', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'keyword_metric_snapshots', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('prospect_score_history', 'score_reason',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_psh_campaign'), table_name='prospect_score_history')
    op.drop_index(op.f('idx_psh_prospect'), table_name='prospect_score_history')
    op.create_index(op.f('ix_prospect_score_history_campaign_id'), 'prospect_score_history', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_prospect_score_history_prospect_id'), 'prospect_score_history', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_prospect_score_history_tenant_id'), 'prospect_score_history', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'prospect_score_history', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recommendations', 'priority',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('recommendations', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('recommendations', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('recommendations', 'impact_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('recommendations', 'effort_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('recommendations', 'supporting_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_rec_status'), table_name='recommendations')
    op.drop_index(op.f('idx_rec_type'), table_name='recommendations')
    op.create_index(op.f('ix_recommendations_entity_id'), 'recommendations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_tenant_id'), 'recommendations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'recommendations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('serp_volatility_snapshots', 'geo',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('serp_volatility_snapshots', 'volatility_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('serp_volatility_snapshots', 'url_churn',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('serp_volatility_snapshots', 'position_changes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('serp_volatility_snapshots', 'feature_changes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('serp_volatility_snapshots', 'top_10_domains',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_svs_captured'), table_name='serp_volatility_snapshots')
    op.drop_index(op.f('idx_svs_keyword'), table_name='serp_volatility_snapshots')
    op.create_index(op.f('ix_serp_volatility_snapshots_keyword'), 'serp_volatility_snapshots', ['keyword'], unique=False)
    op.create_index(op.f('ix_serp_volatility_snapshots_tenant_id'), 'serp_volatility_snapshots', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'serp_volatility_snapshots', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serp_volatility_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_serp_volatility_snapshots_tenant_id'), table_name='serp_volatility_snapshots')
    op.drop_index(op.f('ix_serp_volatility_snapshots_keyword'), table_name='serp_volatility_snapshots')
    op.create_index(op.f('idx_svs_keyword'), 'serp_volatility_snapshots', ['keyword'], unique=False)
    op.create_index(op.f('idx_svs_captured'), 'serp_volatility_snapshots', [sa.literal_column('captured_at DESC')], unique=False)
    op.alter_column('serp_volatility_snapshots', 'top_10_domains',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('serp_volatility_snapshots', 'feature_changes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('serp_volatility_snapshots', 'position_changes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('serp_volatility_snapshots', 'url_churn',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('serp_volatility_snapshots', 'volatility_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('serp_volatility_snapshots', 'geo',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'us'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_recommendations_tenant_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_entity_id'), table_name='recommendations')
    op.create_index(op.f('idx_rec_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('idx_rec_status'), 'recommendations', ['status'], unique=False)
    op.alter_column('recommendations', 'supporting_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('recommendations', 'effort_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('recommendations', 'impact_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('recommendations', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.5'),
               existing_nullable=False)
    op.alter_column('recommendations', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('recommendations', 'priority',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'P2'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'prospect_score_history', type_='foreignkey')
    op.drop_index(op.f('ix_prospect_score_history_tenant_id'), table_name='prospect_score_history')
    op.drop_index(op.f('ix_prospect_score_history_prospect_id'), table_name='prospect_score_history')
    op.drop_index(op.f('ix_prospect_score_history_campaign_id'), table_name='prospect_score_history')
    op.create_index(op.f('idx_psh_prospect'), 'prospect_score_history', ['prospect_id'], unique=False)
    op.create_index(op.f('idx_psh_campaign'), 'prospect_score_history', ['campaign_id'], unique=False)
    op.alter_column('prospect_score_history', 'score_reason',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'scheduled_rescore'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'keyword_metric_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_keyword_metric_snapshots_tenant_id'), table_name='keyword_metric_snapshots')
    op.drop_index(op.f('ix_keyword_metric_snapshots_keyword_id'), table_name='keyword_metric_snapshots')
    op.drop_index(op.f('ix_keyword_metric_snapshots_cluster_id'), table_name='keyword_metric_snapshots')
    op.create_index(op.f('idx_kms_keyword'), 'keyword_metric_snapshots', ['keyword_id'], unique=False)
    op.create_index(op.f('idx_kms_captured'), 'keyword_metric_snapshots', [sa.literal_column('captured_at DESC')], unique=False)
    op.alter_column('keyword_metric_snapshots', 'opportunity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('keyword_metric_snapshots', 'serp_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('keyword_metric_snapshots', 'cpc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('keyword_metric_snapshots', 'difficulty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('keyword_metric_snapshots', 'search_volume',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'campaign_health_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_health_snapshots_tenant_id'), table_name='campaign_health_snapshots')
    op.drop_index(op.f('ix_campaign_health_snapshots_campaign_id'), table_name='campaign_health_snapshots')
    op.create_index(op.f('idx_chs_captured'), 'campaign_health_snapshots', [sa.literal_column('captured_at DESC')], unique=False)
    op.create_index(op.f('idx_chs_campaign'), 'campaign_health_snapshots', ['campaign_id'], unique=False)
    op.alter_column('campaign_health_snapshots', 'snapshot_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('campaign_health_snapshots', 'velocity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('campaign_health_snapshots', 'momentum',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('campaign_health_snapshots', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('campaign_health_snapshots', 'reply_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('campaign_health_snapshots', 'acquisition_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'business_intelligence_events', type_='foreignkey')
    op.drop_index(op.f('ix_business_intelligence_events_tenant_id'), table_name='business_intelligence_events')
    op.drop_index(op.f('ix_business_intelligence_events_event_type'), table_name='business_intelligence_events')
    op.drop_index(op.f('ix_business_intelligence_events_entity_id'), table_name='business_intelligence_events')
    op.drop_index(op.f('ix_business_intelligence_events_domain'), table_name='business_intelligence_events')
    op.create_index(op.f('idx_bie_type'), 'business_intelligence_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_bie_occurred'), 'business_intelligence_events', [sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_bie_domain'), 'business_intelligence_events', ['domain'], unique=False)
    op.alter_column('business_intelligence_events', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('business_intelligence_events', 'action_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('business_intelligence_events', 'delta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('business_intelligence_events', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'info'::character varying"),
               existing_nullable=False)
    op.create_table('operational_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'info'::character varying"), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('operational_events_pkey'))
    )
    op.create_index(op.f('ix_operational_events_type'), 'operational_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_operational_events_created_at'), 'operational_events', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_campaign_timeline_events_tenant_id'), table_name='campaign_timeline_events')
    op.drop_index(op.f('ix_campaign_timeline_events_campaign_id'), table_name='campaign_timeline_events')
    op.drop_table('campaign_timeline_events')
    op.drop_index(op.f('ix_provider_health_metrics_tenant_id'), table_name='provider_health_metrics')
    op.drop_index(op.f('ix_provider_health_metrics_provider_name'), table_name='provider_health_metrics')
    op.drop_table('provider_health_metrics')
    op.drop_index(op.f('ix_compliance_results_tenant_id'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_entity_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_index(op.f('ix_audit_trail_logs_tenant_id'), table_name='audit_trail_logs')
    op.drop_index(op.f('ix_audit_trail_logs_event_type'), table_name='audit_trail_logs')
    op.drop_table('audit_trail_logs')
    # ### end Alembic commands ###
