"""add keyword research table correctly

Revision ID: dc68cfe328e5
Revises: 0d50d93a2214
Create Date: 2026-05-13 22:32:13.484187
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'dc68cfe328e5'
down_revision: Union[str, None] = '0d50d93a2214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_research',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('seed_keyword', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_research_client_id'), 'keyword_research', ['client_id'], unique=False)
    op.create_index(op.f('ix_keyword_research_tenant_id'), 'keyword_research', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_research_tenant_id'), table_name='keyword_research')
    op.drop_index(op.f('ix_keyword_research_client_id'), table_name='keyword_research')
    op.drop_table('keyword_research')
    # ### end Alembic commands ###
