"""
SEO Platform — Phase 14 API: Approval System Endpoints
=====================================================
Manage approval requests generated by the ExecutionEngine.
"""

from __future__ import annotations

from seo_platform.core.auth import get_validated_tenant_id
import uuid
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field

from seo_platform.schemas import APIResponse
from seo_platform.core.rbac import RequirePermission
from seo_platform.services.approval_service import approval_service
from seo_platform.services.orchestrator import orchestrator_service
from seo_platform.core.planning_metrics import seo_approval_wait_seconds, seo_approval_resume_total
import datetime
from seo_platform.models.approval_policy import ApprovalRequest, ApprovalStatus
from seo_platform.core.database import get_tenant_session
from sqlalchemy import select

router = APIRouter()


class ApprovalDecisionRequest(BaseModel):
    approver_id: uuid.UUID
    decision: ApprovalStatus
    comment: str | None = None


class ApprovalResponse(BaseModel):
    id: uuid.UUID
    policy_id: uuid.UUID
    execution_id: uuid.UUID
    requester_id: uuid.UUID
    status: str
    risk_level: str
    action_summary: str
    current_approver_role: str | None = None
    approval_chain: list[Any] | None = None
    approval_history: list[Any] | None = None
    expires_at: str
    final_decision_at: str | None = None
    final_comment: str | None = None
    created_at: str
    updated_at: str | None = None


@router.get("", response_model=APIResponse[list[ApprovalResponse]])
async def list_pending_approvals(tenant_id: uuid.UUID = Depends(get_validated_tenant_id), user = Depends(RequirePermission("approvals:read"))) -> APIResponse[list[ApprovalResponse]]:
    async with get_tenant_session(tenant_id) as session:
        result = await session.execute(
            select(ApprovalRequest).where(ApprovalRequest.tenant_id == tenant_id, ApprovalRequest.status == ApprovalStatus.PENDING)
        )
        approvals = result.scalars().all()
        resp = [ApprovalResponse(
            id=a.id,
            policy_id=a.policy_id,
            execution_id=a.execution_id,
            requester_id=a.requester_id,
            status=a.status.value,
            risk_level=a.risk_level.value,
            action_summary=a.action_summary,
            current_approver_role=a.current_approver_role,
            approval_chain=a.approval_chain,
            approval_history=a.approval_history,
            expires_at=a.expires_at.isoformat(),
            final_decision_at=a.final_decision_at.isoformat() if a.final_decision_at else None,
            final_comment=a.final_comment,
            created_at=a.created_at.isoformat() if a.created_at else None,
            updated_at=a.updated_at.isoformat() if a.updated_at else None,
        ) for a in approvals]
        return APIResponse(data=resp)


@router.post("/{approval_id}/decision", response_model=APIResponse[ApprovalResponse])
async def decide_approval(approval_id: uuid.UUID, request: ApprovalDecisionRequest, tenant_id: uuid.UUID = Depends(get_validated_tenant_id), user = Depends(RequirePermission("approvals:approve"))) -> APIResponse[ApprovalResponse]:
    await approval_service.process_approval(
        tenant_id=tenant_id,
        approval_id=approval_id,
        approver_id=request.approver_id,
        decision=request.decision,
        comment=request.comment,
    )
    # Retrieve updated approval
    async with get_tenant_session(tenant_id) as session:
        approval = await session.get(ApprovalRequest, approval_id)
        if not approval:
            raise HTTPException(status_code=404, detail="Approval not found after processing")
        resp = ApprovalResponse(
            id=approval.id,
            policy_id=approval.policy_id,
            execution_id=approval.execution_id,
            requester_id=approval.requester_id,
            status=approval.status.value,
            risk_level=approval.risk_level.value,
            action_summary=approval.action_summary,
            current_approver_role=approval.current_approver_role,
            approval_chain=approval.approval_chain,
            approval_history=approval.approval_history,
            expires_at=approval.expires_at.isoformat(),
            final_decision_at=approval.final_decision_at.isoformat() if approval.final_decision_at else None,
            final_comment=approval.final_comment,
            created_at=approval.created_at.isoformat() if approval.created_at else None,
            updated_at=approval.updated_at.isoformat() if approval.updated_at else None,
        )
        return APIResponse(data=resp)
