# Temporal Dynamic Configuration — Development
# Relaxed limits for local development
system.forceSearchAttributesCacheRefreshOnRead:
  - value: false
    constraints: {}
limit.maxIDLength:
  - value: 255
    constraints: {}
frontend.keepAliveMaxConnectionAge:
  - value: "10m"
    constraints: {}
