"""
SEO Platform — Phase 14 Models: Operational Memory Layer
===================================================================
Persistent, searchable memory of autonomous decisions, outcomes, and
observations. Designed for semantic recall via vector embeddings stored
in PostgreSQL.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    Index,
    String,
    Text,
    UniqueConstraint,
    text,
    Enum,
    ForeignKey,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from seo_platform.core.database import Base
from seo_platform.models.base import TenantMixin, TimestampMixin

# ---------------------------------------------------------------------------
# Enumerations for memory entry categorisation
# ---------------------------------------------------------------------------

class MemoryEntryType(str, enum.Enum):
    DECISION = "decision"
    OUTCOME = "outcome"
    ACTION = "action"
    APPROVAL = "approval"
    FAILURE = "failure"
    LEARNING = "learning"
    OBSERVATION = "observation"

class MemorySource(str, enum.Enum):
    AGENT_ORCHESTRATOR = "agent_orchestrator"
    PLANNING_ENGINE = "planning_engine"
    EXECUTION_ENGINE = "execution_engine"
    APPROVAL_SERVICE = "approval_service"
    MONITOR = "monitor"

# ---------------------------------------------------------------------------
# Operational Memory Entry – stores a single memory with optional embedding
# ---------------------------------------------------------------------------

class MemoryEntry(Base, TenantMixin, TimestampMixin):
    """Single memory record for semantic recall and timeline reconstruction.

    The ``embedding`` column stores a 1024‑dimensional float vector that can be
    used by Qdrant or Postgres vector extensions for similarity search.
    """

    __tablename__ = "operational_memory"
    __table_args__ = (
        Index("ix_memory_tenant_entry_type_created", "tenant_id", "entry_type", "created_at"),
        Index("ix_memory_tenant_source_created", "tenant_id", "source", "created_at"),
        Index("ix_memory_tenant_tags", "tenant_id", "tags"),
        Index("ix_memory_tenant_created", "tenant_id", "created_at"),
    )

    # Primary key – UUID generated by DB
    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        default=uuid.uuid4,
    )

    # Classification
    entry_type: Mapped[MemoryEntryType] = mapped_column(
        Enum(MemoryEntryType, name="memory_entry_type", create_constraint=True, values_callable=lambda x: [e.value for e in x]),
        nullable=False,
    )
    source: Mapped[MemorySource] = mapped_column(
        Enum(MemorySource, name="memory_source", create_constraint=True, values_callable=lambda x: [e.value for e in x]),
        nullable=False,
    )
    source_execution_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("action_executions.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Human readable summary and detailed JSON context
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    detail: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, server_default=text("'{}'::jsonb"))

    # Tagging & scoring
    tags: Mapped[list[str] | None] = mapped_column(ARRAY(String), nullable=True)
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    impact_score: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Relationships to other memories (optional)
    related_entry_ids: Mapped[list[uuid.UUID] | None] = mapped_column(ARRAY(PG_UUID(as_uuid=True)), nullable=True)

    # Optional semantic embedding – 1024‑dimensional float vector
    embedding: Mapped[list[float] | None] = mapped_column(ARRAY(Float), nullable=True)

    # TTL – optional expiration for time‑bounded memories
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    def __repr__(self) -> str:
        return f"<MemoryEntry {self.id} type={self.entry_type}>"
